"""Add request_type to AdRequest

Revision ID: 0644a80c61bb
Revises: c8c77c53d204
Create Date: 2024-08-12 01:20:18.608347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0644a80c61bb'
down_revision = 'c8c77c53d204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('completion_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.alter_column('completion_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('request_type')

    # ### end Alembic commands ###
