"""user table active filed

Revision ID: 616d24bb1348
Revises: 0644a80c61bb
Create Date: 2024-08-12 12:13:24.039559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616d24bb1348'
down_revision = '0644a80c61bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_flagged')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
