"""influencer update.

Revision ID: e53bdfbdefcc
Revises: a4fec9ffd922
Create Date: 2024-08-10 22:02:32.885203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53bdfbdefcc'
down_revision = 'a4fec9ffd922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
